  version: '3.8'

  services:
    configuration:
      image: configuration:latest
      container_name: configuration
      ports:
        - "9000:9000"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123

    discovery:
      image: discovery:latest # Dockerfile'dan oluşturduğunuz image adı
      container_name: discovery
      ports:
        - "8761:8761"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - EUREKA_INSTANCE_HOSTNAME=discovery
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000  # Config Server URL'si
      depends_on:
        - configuration

    gateway:
      image: gateway:latest # Dockerfile'dan oluşturduğunuz image adı
      container_name: gateway
      ports:
        - "8500:8500"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - EUREKA_INSTANCE_HOSTNAME=gateway
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
      depends_on:
        - configuration
        - discovery

    sale:
      image: sale:latest  # Dockerfile'dan oluşturduğunuz image adı
      container_name: sale
      ports:
        - "8002:8002"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
        - EUREKA_INSTANCE_HOSTNAME=sale
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
      depends_on:
        - configuration
        - discovery


    authentacition:
      image: authentacition:latest  # Dockerfile'dan oluşturduğunuz image adı
      container_name: authentacition
      ports:
        - "8004:8004"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
        - EUREKA_INSTANCE_HOSTNAME=authentacition
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
      depends_on:
        - configuration
        - discovery



    user-management:
      image: user-management:latest  # Dockerfile'dan oluşturduğunuz image adı
      container_name: user-management
      ports:
        - "8008:8008"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
        - EUREKA_INSTANCE_HOSTNAME=user-management
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
      depends_on:
        - configuration
        - discovery


    product:
      image: product:latest # Dockerfile'dan oluşturduğunuz image adı
      container_name: product
      ports:
        - "8000:8000"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
        - EUREKA_INSTANCE_HOSTNAME=product
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
      depends_on:
        - configuration
        - discovery

    report:
      image: report:latest # Dockerfile'dan oluşturduğunuz image adı
      container_name: report
      ports:
        - "8001:8001"
      environment:
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_URI=http://configuration:9000
        - EUREKA_INSTANCE_HOSTNAME=report
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - DB_URL=jdbc:postgresql://postgresq:5432/cashregister
        - DB_USERNAME=postgres
        - DB_PASSWORD=123
      depends_on:
        - configuration
        - discovery



    # Diğer servisler için aynı yapıyı devam ettirin...

    postgresq:
      image: postgres:16
      container_name: postgresq
      environment:
            - POSTGRES_DB=cashregister
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "5050:80"
      depends_on:
        - postgresq
