spring:
  application:
    name: product
  datasource:
    username: [ your_username ]
    password: [ password ]
    driver-class-name: org.postgresql.Driver
    url: [ database_url ]
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

