spring:
  application:
    name: management
  datasource:
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cashregister
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

