server:
  port: 8004

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka


spring:
  application:
    name: authentacition
  config:
    api-endpoints:
      authentacition-url: http://localhost:8004/api/auth


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect