server:
  port: 8004

spring:
  application:
    name: authorization
  config:
    api-endpoints:
      authorization-url: http://localhost:8004/api/auth


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect