
server:
  port: 8500


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sale
          uri: http://localhost:8002
          predicates:
            - Path=/api/v3/sale/**
        - id: product
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/product/**
          filters:
            - name: AuthFilter
        - id: authorization
          uri: http://localhost:8004
          predicates:
            - Path=/api/v6/auth/**



eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka




