spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sale
          uri: http://localhost:8002
          predicates:
            - Path=/api/v3/sale/**
        - id: product
          uri: http://localhost:8000
          predicates:
            - Path=/api/v1/product/**


eureka:
  client:
    register-with-eureka: false

server:
  port: 8500