
server:
  port: 8500


spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sale
          uri: http://localhost:8002
          predicates:
            - Path=/api/sale/**
          filters:
            - name: AuthFilter

        - id: product
          uri: http://localhost:8000
          predicates:
            - Path=/api/product/**
          filters:
            - name: AuthFilter
        - id: category
          uri: http://localhost:8000
          predicates:
            - Path=/api/category/**
          filters:
            - name: AuthFilter

        - id: user-management
          uri: http://localhost:8008
          predicates:
            - Path=/api/user-management/**
          filters:
            - name: AuthFilter

        - id: report
          uri: http://localhost:8001
          predicates:
            - Path=/api/report/**
          filters:
            - name: AuthFilter

        - id: authentacition
          uri: http://localhost:8004
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthFilter



eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka




