
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: sale

  config:
    api-endpoints:
      sale-url: http://localhost:8002/api/sale
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cashregister
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect