
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: sale

  config:
    api-endpoints:
      sale-url: http://localhost:8002/api/v3/sale
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
